# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.20.0
import dataclasses
import datetime
import enum
from typing import Optional
import uuid


class SettingsValueType(str, enum.Enum):
    BOOL = "bool"
    STR = "str"
    INT = "int"
    FLOAT = "float"


@dataclasses.dataclass()
class Session:
    id: uuid.UUID
    username: str
    issued_at: datetime.datetime


@dataclasses.dataclass()
class Setting:
    key: str
    value_type: SettingsValueType
    value_bool: Optional[bool]
    value_str: Optional[str]
    value_int: Optional[int]
    value_float: Optional[float]


@dataclasses.dataclass()
class User:
    username: str
    password: str
    email: str
    name: str
