# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.20.0
import dataclasses
import datetime
import enum
from typing import Any
import uuid


class Widgets(str, enum.Enum):
    TEXT = "text"
    CHECKBOX = "checkbox"
    SELECT = "select"


@dataclasses.dataclass()
class Form:
    id: int
    owner: str
    source: int
    created_at: datetime.datetime


@dataclasses.dataclass()
class FormField:
    id: int
    form: int
    table_name: str
    field_name: str
    weight: int
    widget: Widgets
    widget_data: Any


@dataclasses.dataclass()
class Session:
    id: uuid.UUID
    username: str
    issued_at: datetime.datetime


@dataclasses.dataclass()
class Source:
    id: int
    owner: str
    conn_string: str
    created_at: datetime.datetime


@dataclasses.dataclass()
class User:
    username: str
    password: str
    email: str
    name: str
